//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetWallet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnglishStringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public EnglishStringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JetWallet.Resources.EnglishStringResource", typeof(EnglishStringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Wallet.
        /// </summary>
        public static string CreateWallet_CreateWallet {
            get {
                return ResourceManager.GetString("CreateWallet_CreateWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (optional).
        /// </summary>
        public static string CreateWallet_Desc {
            get {
                return ResourceManager.GetString("CreateWallet_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wallet is already active. Would you like to close the current active wallet and make this new wallet active ?.
        /// </summary>
        public static string CreateWallet_Dialog_ActiveWallet_Message {
            get {
                return ResourceManager.GetString("CreateWallet_Dialog_ActiveWallet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        public static string CreateWallet_Dialog_ActiveWallet_Title {
            get {
                return ResourceManager.GetString("CreateWallet_Dialog_ActiveWallet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field is required. Wallet password must be at least *NUM* characters..
        /// </summary>
        public static string CreateWallet_Dialog_Insufficient_Message {
            get {
                return ResourceManager.GetString("CreateWallet_Dialog_Insufficient_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Insufficient.
        /// </summary>
        public static string CreateWallet_Dialog_Insufficient_Title {
            get {
                return ResourceManager.GetString("CreateWallet_Dialog_Insufficient_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name field is required. Password field is required and must be at least *NUM* characters..
        /// </summary>
        public static string CreateWallet_Dialog_Invalid_Message {
            get {
                return ResourceManager.GetString("CreateWallet_Dialog_Invalid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &amp; Password Required.
        /// </summary>
        public static string CreateWallet_Dialog_Invalid_Title {
            get {
                return ResourceManager.GetString("CreateWallet_Dialog_Invalid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name field cannot be empty..
        /// </summary>
        public static string CreateWallet_Dialog_NameEmpty_Message {
            get {
                return ResourceManager.GetString("CreateWallet_Dialog_NameEmpty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string CreateWallet_Dialog_NameEmpty_Title {
            get {
                return ResourceManager.GetString("CreateWallet_Dialog_NameEmpty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the following fields to create a new wallet.
        /// </summary>
        public static string CreateWallet_Message {
            get {
                return ResourceManager.GetString("CreateWallet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name your wallet *.
        /// </summary>
        public static string CreateWallet_Name {
            get {
                return ResourceManager.GetString("CreateWallet_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. Johny&apos;s Wallet.
        /// </summary>
        public static string CreateWallet_NameExample {
            get {
                return ResourceManager.GetString("CreateWallet_NameExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password protect your wallet *.
        /// </summary>
        public static string CreateWallet_Pass {
            get {
                return ResourceManager.GetString("CreateWallet_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testnet *.
        /// </summary>
        public static string CreateWallet_Testnet {
            get {
                return ResourceManager.GetString("CreateWallet_Testnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not sure? Leave unchecked.
        /// </summary>
        public static string CreateWallet_TestnetMessage {
            get {
                return ResourceManager.GetString("CreateWallet_TestnetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create A New Wallet.
        /// </summary>
        public static string CreateWallet_Title {
            get {
                return ResourceManager.GetString("CreateWallet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Wallet File does not exist at specified location *path*. This wallet will now close..
        /// </summary>
        public static string Error_A100 {
            get {
                return ResourceManager.GetString("Error_A100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not lock wallet..
        /// </summary>
        public static string Error_A100_Lock {
            get {
                return ResourceManager.GetString("Error_A100_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change wallet password..
        /// </summary>
        public static string Error_A100_Pass {
            get {
                return ResourceManager.GetString("Error_A100_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already exists Jet Wallet files in the specified path *path* &amp; *recoverypath*. Please give your wallet a new name or delete the existing Jet Wallet Files..
        /// </summary>
        public static string Error_A200 {
            get {
                return ResourceManager.GetString("Error_A200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Jet Wallet file already exists with the name &apos;*name*&apos; in the specified path  *path*. Please give your wallet a new name. Note that the recovery wallet file for &apos;*name*&apos; is missing..
        /// </summary>
        public static string Error_A201 {
            get {
                return ResourceManager.GetString("Error_A201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Jet Wallet recovery file already exists with the name &apos;*name*&apos; in the specified path *recoverypath*. Please give your wallet a new name..
        /// </summary>
        public static string Error_A202 {
            get {
                return ResourceManager.GetString("Error_A202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Files failed to update. Wallet Files do not exist at specified location..
        /// </summary>
        public static string Error_A300 {
            get {
                return ResourceManager.GetString("Error_A300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previously active wallet failed to load. The wallet file could not be found..
        /// </summary>
        public static string Error_A400 {
            get {
                return ResourceManager.GetString("Error_A400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file selected is a Jet Wallet recovery file. You will need the respected Recovery Phrase to unlock the wallet. If you are trying to recover a wallet, use the &apos;Recover Wallet&apos; option in the File menu tab..
        /// </summary>
        public static string Error_A500 {
            get {
                return ResourceManager.GetString("Error_A500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type. Jet Wallet files are of the form &apos;.jet&apos; ie) mywallet.jet.
        /// </summary>
        public static string Error_A501 {
            get {
                return ResourceManager.GetString("Error_A501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect file type. The file must be a Jet Wallet recovery file. ie) mywallet.recover.jet. Jet Wallet recovery files are hidden by default. You may have to make them visible..
        /// </summary>
        public static string Error_A502 {
            get {
                return ResourceManager.GetString("Error_A502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type. Jet Wallet Recovery files are of the form &apos;.recover.jet&apos; ie) mywallet.recover.jet.
        /// </summary>
        public static string Error_A503 {
            get {
                return ResourceManager.GetString("Error_A503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wallet is already active. Would you like to close the present active wallet and make this wallet active?.
        /// </summary>
        public static string Main_Dialog_ActiveWallet_Message {
            get {
                return ResourceManager.GetString("Main_Dialog_ActiveWallet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Active Wallet?.
        /// </summary>
        public static string Main_Dialog_ActiveWallet_Title {
            get {
                return ResourceManager.GetString("Main_Dialog_ActiveWallet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction History.
        /// </summary>
        public static string Main_Info_Active {
            get {
                return ResourceManager.GetString("Main_Info_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Wallet Active.
        ///Import or Create a Wallet by clicking on File in the Menu Bar..
        /// </summary>
        public static string Main_Info_Inactive {
            get {
                return ResourceManager.GetString("Main_Info_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string Main_Menu_About {
            get {
                return ResourceManager.GetString("Main_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Wallet.
        /// </summary>
        public static string Main_Menu_Close {
            get {
                return ResourceManager.GetString("Main_Menu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Scheme.
        /// </summary>
        public static string Main_Menu_ColorScheme {
            get {
                return ResourceManager.GetString("Main_Menu_ColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Main_Menu_Exit {
            get {
                return ResourceManager.GetString("Main_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string Main_Menu_File {
            get {
                return ResourceManager.GetString("Main_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Wallet.
        /// </summary>
        public static string Main_Menu_Import {
            get {
                return ResourceManager.GetString("Main_Menu_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Main_Menu_Language {
            get {
                return ResourceManager.GetString("Main_Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Wallet.
        /// </summary>
        public static string Main_Menu_Manage {
            get {
                return ResourceManager.GetString("Main_Menu_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Wallet.
        /// </summary>
        public static string Main_Menu_New {
            get {
                return ResourceManager.GetString("Main_Menu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Wallet.
        /// </summary>
        public static string Main_Menu_Recover {
            get {
                return ResourceManager.GetString("Main_Menu_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string Main_Menu_Settings {
            get {
                return ResourceManager.GetString("Main_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Wallet.
        /// </summary>
        public static string Main_NoWallet {
            get {
                return ResourceManager.GetString("Main_NoWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Bitcoin.
        /// </summary>
        public static string Main_Receive {
            get {
                return ResourceManager.GetString("Main_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Bitcoin.
        /// </summary>
        public static string Main_Send {
            get {
                return ResourceManager.GetString("Main_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your Wallet Password.
        /// </summary>
        public static string ManageWallet_ChangeMessage {
            get {
                return ResourceManager.GetString("ManageWallet_ChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ManageWallet_ChangePass {
            get {
                return ResourceManager.GetString("ManageWallet_ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ManageWallet_ConfPass {
            get {
                return ResourceManager.GetString("ManageWallet_ConfPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Current Password.
        /// </summary>
        public static string ManageWallet_CurrPass {
            get {
                return ResourceManager.GetString("ManageWallet_CurrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All password fields are required. Please try again..
        /// </summary>
        public static string ManageWallet_Dialog_Incomplete_Message {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Incomplete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Fields.
        /// </summary>
        public static string ManageWallet_Dialog_Incomplete_Title {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Incomplete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password entered was incorrect. Please try again..
        /// </summary>
        public static string ManageWallet_Dialog_Incorrect_Message {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Incorrect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Current Password.
        /// </summary>
        public static string ManageWallet_Dialog_Incorrect_Title {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Incorrect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password needs to be at least *NUM* characters. Please try again..
        /// </summary>
        public static string ManageWallet_Dialog_Insufficient_Message {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Insufficient_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient New Password.
        /// </summary>
        public static string ManageWallet_Dialog_Insufficient_Title {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Insufficient_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current wallet password entered is incorrect and the confirmation password did not match the new password. Please try again..
        /// </summary>
        public static string ManageWallet_Dialog_Invalid_Message {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Invalid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Inputs.
        /// </summary>
        public static string ManageWallet_Dialog_Invalid_Title {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Invalid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password cannot match the current password. Please try again..
        /// </summary>
        public static string ManageWallet_Dialog_Match_Message {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Match_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current and New Password Match.
        /// </summary>
        public static string ManageWallet_Dialog_Match_Title {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Match_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet password changed successfuly..
        /// </summary>
        public static string ManageWallet_Dialog_Success_Message {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string ManageWallet_Dialog_Success_Title {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match. Please try again..
        /// </summary>
        public static string ManageWallet_Dialog_Unequal_Message {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Unequal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Do Not Match.
        /// </summary>
        public static string ManageWallet_Dialog_Unequal_Title {
            get {
                return ResourceManager.GetString("ManageWallet_Dialog_Unequal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password lock your wallet.
        /// </summary>
        public static string ManageWallet_LockMessage {
            get {
                return ResourceManager.GetString("ManageWallet_LockMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Wallet.
        /// </summary>
        public static string ManageWallet_LockWallet {
            get {
                return ResourceManager.GetString("ManageWallet_LockWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Password.
        /// </summary>
        public static string ManageWallet_NewPass {
            get {
                return ResourceManager.GetString("ManageWallet_NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Wallet.
        /// </summary>
        public static string ManageWallet_Title {
            get {
                return ResourceManager.GetString("ManageWallet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wallet &apos;*name*&apos; will not be loaded..
        /// </summary>
        public static string PromptPassword_DialogMessage {
            get {
                return ResourceManager.GetString("PromptPassword_DialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        public static string PromptPassword_DialogTitle {
            get {
                return ResourceManager.GetString("PromptPassword_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Please try again.
        ///Please enter the password associated with the wallet &apos;*name*&apos;.
        /// </summary>
        public static string PromptPassword_IncorrectMessage {
            get {
                return ResourceManager.GetString("PromptPassword_IncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password associated with the wallet &apos;*name*&apos;.
        /// </summary>
        public static string PromptPassword_Message {
            get {
                return ResourceManager.GetString("PromptPassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Wallet Password.
        /// </summary>
        public static string PromptPassword_Title {
            get {
                return ResourceManager.GetString("PromptPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Wallet.
        /// </summary>
        public static string PromptPassword_UnlockWallet {
            get {
                return ResourceManager.GetString("PromptPassword_UnlockWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RecoverWallet_Dialog_Incorrect_Message {
            get {
                return ResourceManager.GetString("RecoverWallet_Dialog_Incorrect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful Attempt.
        /// </summary>
        public static string RecoverWallet_Dialog_Incorrect_Title {
            get {
                return ResourceManager.GetString("RecoverWallet_Dialog_Incorrect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, the wallet &apos;*name*&apos; was retrieved successfully..
        /// </summary>
        public static string RecoverWallet_Dialog_Success_Message {
            get {
                return ResourceManager.GetString("RecoverWallet_Dialog_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string RecoverWallet_Dialog_Success_Title {
            get {
                return ResourceManager.GetString("RecoverWallet_Dialog_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to recover the wallet &apos;*name*&apos;.
        /// </summary>
        public static string RecoverWallet_Header {
            get {
                return ResourceManager.GetString("RecoverWallet_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Recovery Phrase associated with the wallet in the text box below..
        /// </summary>
        public static string RecoverWallet_Message {
            get {
                return ResourceManager.GetString("RecoverWallet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to leave a space after each word.
        /// </summary>
        public static string RecoverWallet_Note {
            get {
                return ResourceManager.GetString("RecoverWallet_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string RecoverWallet_Recover {
            get {
                return ResourceManager.GetString("RecoverWallet_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Wallet.
        /// </summary>
        public static string RecoverWallet_Title {
            get {
                return ResourceManager.GetString("RecoverWallet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Phrase.
        /// </summary>
        public static string RecoveryPhrase_Header {
            get {
                return ResourceManager.GetString("RecoveryPhrase_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following bold text of words is your newly created wallet&apos;s &apos;Recovery Phrase&apos;. The Recovery Phrase is used to recover your wallet when you forget/misplace your password..
        /// </summary>
        public static string RecoveryPhrase_Intro {
            get {
                return ResourceManager.GetString("RecoveryPhrase_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the only time you will have access to the Recovery Phrase so store it somewhere safe and away from prying eyes. This phrase is the only alternative to recover a wallet who&apos;s password is forgotton/lost..
        /// </summary>
        public static string RecoveryPhrase_Outro {
            get {
                return ResourceManager.GetString("RecoveryPhrase_Outro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Recovery Phrase.
        /// </summary>
        public static string RecoveryPhrase_Title {
            get {
                return ResourceManager.GetString("RecoveryPhrase_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string SetPassword_ConfPass {
            get {
                return ResourceManager.GetString("SetPassword_ConfPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set A New Password.
        /// </summary>
        public static string SetPassword_Header {
            get {
                return ResourceManager.GetString("SetPassword_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now that you have recovered your wallet, give it a new password..
        /// </summary>
        public static string SetPassword_Message {
            get {
                return ResourceManager.GetString("SetPassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string SetPassword_NewPass {
            get {
                return ResourceManager.GetString("SetPassword_NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set New Password.
        /// </summary>
        public static string SetPassword_SetNewPass {
            get {
                return ResourceManager.GetString("SetPassword_SetNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set New Wallet Password.
        /// </summary>
        public static string SetPassword_Title {
            get {
                return ResourceManager.GetString("SetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jet Wallet - Notice.
        /// </summary>
        public static string SimpleDialog_Title {
            get {
                return ResourceManager.GetString("SimpleDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Wallet.
        /// </summary>
        public static string Welcome_CreateWallet {
            get {
                return ResourceManager.GetString("Welcome_CreateWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Jet Wallet.
        /// </summary>
        public static string Welcome_Header {
            get {
                return ResourceManager.GetString("Welcome_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for downloading Jet Wallet. Jet Wallet is a Bitcoin Wallet that you can use to send and receive Bitcoin securely. You will find that this wallet software is quite defensive for good reason..
        /// </summary>
        public static string Welcome_IntroMessage {
            get {
                return ResourceManager.GetString("Welcome_IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to use a strong password when creating a wallet. If you forget your wallet password, you can recover your wallet using the &apos;Recovery Phrase&apos; uniqely generated for each wallet created..
        /// </summary>
        public static string Welcome_OutroMessage {
            get {
                return ResourceManager.GetString("Welcome_OutroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the major motivations of Bitcoin was to give people the ability to control and personally manage their own funds. This software was built to support that motivation. It is also open source..
        /// </summary>
        public static string Welcome_QuoteMessage {
            get {
                return ResourceManager.GetString("Welcome_QuoteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Welcome_Skip {
            get {
                return ResourceManager.GetString("Welcome_Skip", resourceCulture);
            }
        }
    }
}
