//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JetWallet_v1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JetWallet_v1.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string English_Cancel {
            get {
                return ResourceManager.GetString("English_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Wallet.
        /// </summary>
        internal static string English_CreateWallet_CreateWallet {
            get {
                return ResourceManager.GetString("English_CreateWallet_CreateWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (optional).
        /// </summary>
        internal static string English_CreateWallet_Desc {
            get {
                return ResourceManager.GetString("English_CreateWallet_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the following fields to create a new wallet.
        /// </summary>
        internal static string English_CreateWallet_Message {
            get {
                return ResourceManager.GetString("English_CreateWallet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name your wallet *.
        /// </summary>
        internal static string English_CreateWallet_Name {
            get {
                return ResourceManager.GetString("English_CreateWallet_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg. Johny&apos;s Wallet.
        /// </summary>
        internal static string English_CreateWallet_NameExample {
            get {
                return ResourceManager.GetString("English_CreateWallet_NameExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password protect your wallet *.
        /// </summary>
        internal static string English_CreateWallet_Pass {
            get {
                return ResourceManager.GetString("English_CreateWallet_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testnet *.
        /// </summary>
        internal static string English_CreateWallet_Testnet {
            get {
                return ResourceManager.GetString("English_CreateWallet_Testnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not sure? Leave unchecked.
        /// </summary>
        internal static string English_CreateWallet_TestnetMessage {
            get {
                return ResourceManager.GetString("English_CreateWallet_TestnetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create A New Wallet.
        /// </summary>
        internal static string English_CreateWallet_Title {
            get {
                return ResourceManager.GetString("English_CreateWallet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Wallet File does not exist at specified location *path*. This wallet will now close..
        /// </summary>
        internal static string English_Error_A100 {
            get {
                return ResourceManager.GetString("English_Error_A100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not lock wallet..
        /// </summary>
        internal static string English_Error_A100_Lock {
            get {
                return ResourceManager.GetString("English_Error_A100_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change wallet password..
        /// </summary>
        internal static string English_Error_A100_Pass {
            get {
                return ResourceManager.GetString("English_Error_A100_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your Wallet Password.
        /// </summary>
        internal static string English_ManageWallet_ChangeMessage {
            get {
                return ResourceManager.GetString("English_ManageWallet_ChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string English_ManageWallet_ChangePass {
            get {
                return ResourceManager.GetString("English_ManageWallet_ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        internal static string English_ManageWallet_ConfPass {
            get {
                return ResourceManager.GetString("English_ManageWallet_ConfPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Current Password.
        /// </summary>
        internal static string English_ManageWallet_CurrPass {
            get {
                return ResourceManager.GetString("English_ManageWallet_CurrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All password fields are required. Please try again..
        /// </summary>
        internal static string English_ManageWallet_Dialog_Incomplete_Message {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Incomplete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Fields.
        /// </summary>
        internal static string English_ManageWallet_Dialog_Incomplete_Title {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Incomplete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password entered was incorrect. Please try again..
        /// </summary>
        internal static string English_ManageWallet_Dialog_Incorrect_Message {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Incorrect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Current Password.
        /// </summary>
        internal static string English_ManageWallet_Dialog_Incorrect_Title {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Incorrect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password needs to be at least 4 characters. Please try again..
        /// </summary>
        internal static string English_ManageWallet_Dialog_Insufficient_Message {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Insufficient_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient New Password.
        /// </summary>
        internal static string English_ManageWallet_Dialog_Insufficient_Title {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Insufficient_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current wallet password entered is incorrect and the confirmation password did not match the new password. Please try again..
        /// </summary>
        internal static string English_ManageWallet_Dialog_Invalid_Message {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Invalid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Inputs.
        /// </summary>
        internal static string English_ManageWallet_Dialog_Invalid_Title {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Invalid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password cannot match the current password. Please try again..
        /// </summary>
        internal static string English_ManageWallet_Dialog_Match_Message {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Match_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current and New Password Match.
        /// </summary>
        internal static string English_ManageWallet_Dialog_Match_Title {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Match_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet password changed successfuly..
        /// </summary>
        internal static string English_ManageWallet_Dialog_Success_Message {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string English_ManageWallet_Dialog_Success_Title {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match. Please try again..
        /// </summary>
        internal static string English_ManageWallet_Dialog_Unequal_Message {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Unequal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Do Not Match.
        /// </summary>
        internal static string English_ManageWallet_Dialog_Unequal_Title {
            get {
                return ResourceManager.GetString("English_ManageWallet_Dialog_Unequal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password lock your wallet.
        /// </summary>
        internal static string English_ManageWallet_LockMessage {
            get {
                return ResourceManager.GetString("English_ManageWallet_LockMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Wallet.
        /// </summary>
        internal static string English_ManageWallet_LockWallet {
            get {
                return ResourceManager.GetString("English_ManageWallet_LockWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Password.
        /// </summary>
        internal static string English_ManageWallet_NewPass {
            get {
                return ResourceManager.GetString("English_ManageWallet_NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Wallet.
        /// </summary>
        internal static string English_ManageWallet_Title {
            get {
                return ResourceManager.GetString("English_ManageWallet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string English_Ok {
            get {
                return ResourceManager.GetString("English_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wallet &apos;*name*&apos; will not be loaded..
        /// </summary>
        internal static string English_PromptPassword_DialogMessage {
            get {
                return ResourceManager.GetString("English_PromptPassword_DialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        internal static string English_PromptPassword_DialogTitle {
            get {
                return ResourceManager.GetString("English_PromptPassword_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Please try again.
        ///Please enter the password associated with the wallet &apos;*name*&apos;.
        /// </summary>
        internal static string English_PromptPassword_IncorrectMessage {
            get {
                return ResourceManager.GetString("English_PromptPassword_IncorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password associated with the wallet &apos;*name*&apos;.
        /// </summary>
        internal static string English_PromptPassword_Message {
            get {
                return ResourceManager.GetString("English_PromptPassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Wallet Password.
        /// </summary>
        internal static string English_PromptPassword_Title {
            get {
                return ResourceManager.GetString("English_PromptPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Wallet.
        /// </summary>
        internal static string English_PromptPassword_UnlockWallet {
            get {
                return ResourceManager.GetString("English_PromptPassword_UnlockWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to recover the wallet &apos;*name*&apos;.
        /// </summary>
        internal static string English_RecoverWallet_Header {
            get {
                return ResourceManager.GetString("English_RecoverWallet_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Recovery Phrase associated with the wallet in the text box below..
        /// </summary>
        internal static string English_RecoverWallet_Message {
            get {
                return ResourceManager.GetString("English_RecoverWallet_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to leave a space after each word.
        /// </summary>
        internal static string English_RecoverWallet_Note {
            get {
                return ResourceManager.GetString("English_RecoverWallet_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        internal static string English_RecoverWallet_Recover {
            get {
                return ResourceManager.GetString("English_RecoverWallet_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Wallet.
        /// </summary>
        internal static string English_RecoverWallet_Title {
            get {
                return ResourceManager.GetString("English_RecoverWallet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Phrase.
        /// </summary>
        internal static string English_RecoveryPhrase_Header {
            get {
                return ResourceManager.GetString("English_RecoveryPhrase_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following bold text of words is your newly created wallet&apos;s &apos;Recovery Phrase&apos;. The Recovery Phrase is used to recover your wallet when you forget/misplace your password..
        /// </summary>
        internal static string English_RecoveryPhrase_Intro {
            get {
                return ResourceManager.GetString("English_RecoveryPhrase_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the only time you will have access to the Recovery Phrase so store it somewhere safe and away from prying eyes. This phrase is the only alternative to recover a wallet who&apos;s password is forgotton/lost..
        /// </summary>
        internal static string English_RecoveryPhrase_Outro {
            get {
                return ResourceManager.GetString("English_RecoveryPhrase_Outro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Recovery Phrase.
        /// </summary>
        internal static string English_RecoveryPhrase_Title {
            get {
                return ResourceManager.GetString("English_RecoveryPhrase_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string English_SetPassword_ConfPass {
            get {
                return ResourceManager.GetString("English_SetPassword_ConfPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set A New Password.
        /// </summary>
        internal static string English_SetPassword_Header {
            get {
                return ResourceManager.GetString("English_SetPassword_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now that you have recovered your wallet, give it a new password..
        /// </summary>
        internal static string English_SetPassword_Message {
            get {
                return ResourceManager.GetString("English_SetPassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string English_SetPassword_NewPass {
            get {
                return ResourceManager.GetString("English_SetPassword_NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set New Password.
        /// </summary>
        internal static string English_SetPassword_SetNewPass {
            get {
                return ResourceManager.GetString("English_SetPassword_SetNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set New Wallet Password.
        /// </summary>
        internal static string English_SetPassword_Title {
            get {
                return ResourceManager.GetString("English_SetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jet Wallet - Notice.
        /// </summary>
        internal static string English_SimpleDialog_Title {
            get {
                return ResourceManager.GetString("English_SimpleDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Wallet.
        /// </summary>
        internal static string English_Welcome_CreateWallet {
            get {
                return ResourceManager.GetString("English_Welcome_CreateWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Jet Wallet.
        /// </summary>
        internal static string English_Welcome_Header {
            get {
                return ResourceManager.GetString("English_Welcome_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for downloading Jet Wallet. Jet Wallet is a Bitcoin Wallet that you can use to send and receive Bitcoin securely. You will find that this wallet software is quite defensive for good reason..
        /// </summary>
        internal static string English_Welcome_IntroMessage {
            get {
                return ResourceManager.GetString("English_Welcome_IntroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to use a strong password when creating a wallet. If you forget your wallet password, you can recover your wallet using the &apos;Recovery Phrase&apos; uniqely generated for each wallet created..
        /// </summary>
        internal static string English_Welcome_OutroMessage {
            get {
                return ResourceManager.GetString("English_Welcome_OutroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the major motivations of Bitcoin was to give people the ability to control and personally manage their own funds. This software was built to support that motivation. It is also open source..
        /// </summary>
        internal static string English_Welcome_QuoteMessage {
            get {
                return ResourceManager.GetString("English_Welcome_QuoteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string English_Welcome_Skip {
            get {
                return ResourceManager.GetString("English_Welcome_Skip", resourceCulture);
            }
        }
    }
}
